### PR TITLE
Bump up php version requirement

### PR DESCRIPTION
**Pull request by nasyrov**

### CODE REVIEW

**Comment by vvasilev-** [comment]
Hi @nasyrov,

Thanks for your contribution! 
Can you explain why bumping of PHP version is necessary? 😄

**Comment by nasyrov** [comment]
hi @vvasilev- ,

PHP 5.3 end of life is 14 Aug 2014, see more at http://php.net/eol.php

**Comment by vvasilev-** [comment]
@nasyrov,

We're aware of that but many of our projects are still running on hosts with PHP 5.3 and this change will break the things on our end. So we'll prefer to stick with the current minimum version, this way we can safely upgrade our projects to Carbon Fields 3.0. Hope that makes sense to you. Thanks again for your contribution!

**Comment by nasyrov** [comment]
Hi @vvasilev- ,

Thanks!

**Pull request closed without merging**
